### ISSUE TITLE
[ BUG ] Change Favicon 

### ISSUE THREAD

**Issue by RuthwikReddy09** [nitin-pandita/Yoga#6]
### Description

The current favicon is the default Vite favicon. Replace it with a new favicon or the logo of the application.

### Steps to Reproduce

1. Open https://yoga-sand.vercel.app/
2. Favicon is visible on tabs section 

### Screenshots

<img width="122" alt="Screenshot 2023-08-27 094359" src="https://github.com/nitin-pandita/Yoga/assets/126862059/9c32559a-4958-49fc-8861-401bbdfd06e0">

**Comment by nitin-pandita** [comment]
Would you like to work on this issue ?

**Comment by Abhi1234-tech** [comment]
@nitin-pandita Please let me know if I can work on this if @RuthwikReddy09 is not doing it.

**Comment by RuthwikReddy09** [comment]
@Abhi1234-tech Iam not working on it . you can work on this issue
